In [1]:
import tensorflow as tf


In [2]:
W=tf.Variable([[1,2,3],[4,5,6]],dtype=tf.float32,name='weights')
b=tf.Variable([[1],[4],[9]],dtype=tf.float32,name='bias')

In [3]:
saver=tf.train.Saver()

In [4]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print('weights:', sess.run(W))
    print('Biases: ', sess.run(b))
    save_patch=saver.save(sess,"saving_ppp/save_variables.ckpt")
    print('variables are saved to ..',save_patch)

weights: [[ 1.  2.  3.]
 [ 4.  5.  6.]]
Biases:  [[ 1.]
 [ 4.]
 [ 9.]]
variables are saved to .. saving_ppp/save_variables.ckpt


# Restore your variables again, but we have have to define those variables again with same shape, no need init

In [5]:
import tensorflow as tf
tf.reset_default_graph() ## thhis commánd is important
W=tf.Variable(tf.random_normal([2,3]),dtype=tf.float32,name='weights')
b=tf.Variable(tf.random_normal([3,1]),dtype=tf.float32,name='bias')

In [6]:
saver=tf.train.Saver()

In [10]:

with tf.Session() as sess:
    saver.restore(sess, "saving_ppp/save_variables.ckpt")
    print("weights:", sess.run(W))
    print("biases:", sess.run(b))
    weight=sess.run(W)
    print(weight)

INFO:tensorflow:Restoring parameters from saving_ppp/save_variables.ckpt
weights: [[ 1.  2.  3.]
 [ 4.  5.  6.]]
biases: [[ 1.]
 [ 4.]
 [ 9.]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
